sudo: false  # Force container-based builds.
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.cache/pip
services:
  - elasticsearch
  - redis-server
install:
  - pip install --upgrade pip --cache-dir $HOME/.pip-cache/
  - pip install coveralls --cache-dir $HOME/.pip-cache/
  - pip install flake8 --cache-dir $HOME/.pip-cache/
  - pip install -r requirements-dev.txt --cache-dir $HOME/.pip-cache/
  - pip install -e . --cache-dir $HOME/.pip-cache/
script:
  - flake8
  - py.test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
    secure: "insert encrypted pypi password here"
  on:
    tags: true
    all_branches: true
