sudo: false  # Force container-based builds.
language: python
python:
  - '2.7'
cache:
  - pip

jobs:
  include:
    - stage: test
      services:
        - elasticsearch
        - redis-server
      before_install:
        - pip install --upgrade pip
      install:
        - pip install -e .
        - pip install -r requirements-dev.txt
        - pip install coveralls
      script:
        - flake8
        - py.test
      after_success:
        - coveralls
      deploy:
        provider: pypi
        user: Praekelt
        password:
          # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
          secure: "insert encrypted pypi password here"
        on:
          tags: true
          all_branches: true

    - stage: docker
      sudo: required
      dist: trusty
      services: [docker]
      install:
        # Update docker-engine: we need at least 17.05.0 to use an argument in
        # the FROM tag
        - sudo apt-get update
        - sudo apt-get install -y -o Dpkg::Options::="--force-confold" docker-engine
      before_script:
        - molo_version="$(sed -nE 's/^molo\.core==(.*)$/\1/p' requirements.txt)"
      script:
        - docker build --tag praekeltorg/molo-gem --build-arg MOLO_VERSION="$molo_version" .
