language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install flake8
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install git+git://github.com/praekelt/molo.comments@feature/issue-2-package-threaded-comments#egg=molo.comments
script:
  - flake8
  - py.test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
    secure: "insert encrypted pypi password here"
  on:
    tags: true
    all_branches: true
