sudo: false  # Force container-based builds.
language: python
python:
  - "2.7"
cache:
  - pip
services:
  - elasticsearch
  - redis-server
before_install:
  - pip install --upgrade pip
install:
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  - py.test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Praekelt
  password:
    # NOTE: See http://docs.travis-ci.com/user/encryption-keys/ for more info.
    secure: "insert encrypted pypi password here"
  on:
    tags: true
    all_branches: true
